# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 6.4.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QMainWindow, QMenu, QMenuBar,
    QSizePolicy, QStatusBar, QTextEdit, QToolBar,
    QWidget)
# import Image_rc

class Ui_TextEditor(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(793, 613)
        self.actionNew = QAction(MainWindow)
        self.actionNew.setObjectName(u"actionNew")
        icon = QIcon()
        icon.addFile("./images/new-file.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionNew.setIcon(icon)
        self.actionOpen = QAction(MainWindow)
        self.actionOpen.setObjectName(u"actionOpen")
        icon1 = QIcon()
        icon1.addFile("./images/open_file.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionOpen.setIcon(icon1)
        self.actionSave = QAction(MainWindow)
        self.actionSave.setObjectName(u"actionSave")
        icon2 = QIcon()
        icon2.addFile("./images/Save.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionSave.setIcon(icon2)
        self.actionSave_As = QAction(MainWindow)
        self.actionSave_As.setObjectName(u"actionSave_As")
        icon3 = QIcon()
        icon3.addFile("./images/Save-as-main.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionSave_As.setIcon(icon3)
        self.actionPrint = QAction(MainWindow)
        self.actionPrint.setObjectName(u"actionPrint")
        icon4 = QIcon()
        icon4.addFile("./images/print.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionPrint.setIcon(icon4)
        self.actionPrint_Preview = QAction(MainWindow)
        self.actionPrint_Preview.setObjectName(u"actionPrint_Preview")
        icon5 = QIcon()
        icon5.addFile("./images/print-preview.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionPrint_Preview.setIcon(icon5)
        self.actionExport_As_PDF = QAction(MainWindow)
        self.actionExport_As_PDF.setObjectName(u"actionExport_As_PDF")
        icon6 = QIcon()
        icon6.addFile("./images/pdf.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionExport_As_PDF.setIcon(icon6)
        self.actionExit = QAction(MainWindow)
        self.actionExit.setObjectName(u"actionExit")
        icon7 = QIcon()
        icon7.addFile("./images/exit.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionExit.setIcon(icon7)
        self.actionCopy = QAction(MainWindow)
        self.actionCopy.setObjectName(u"actionCopy")
        icon8 = QIcon()
        icon8.addFile("./images/Copy.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionCopy.setIcon(icon8)
        self.actionCut = QAction(MainWindow)
        self.actionCut.setObjectName(u"actionCut")
        icon9 = QIcon()
        icon9.addFile("./images/Cut.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionCut.setIcon(icon9)
        self.actionPaste = QAction(MainWindow)
        self.actionPaste.setObjectName(u"actionPaste")
        icon10 = QIcon()
        icon10.addFile("./images/Paste.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionPaste.setIcon(icon10)
        self.actionUndo = QAction(MainWindow)
        self.actionUndo.setObjectName(u"actionUndo")
        icon11 = QIcon()
        icon11.addFile("./images/undo.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionUndo.setIcon(icon11)
        self.actionRedo = QAction(MainWindow)
        self.actionRedo.setObjectName(u"actionRedo")
        icon12 = QIcon()
        icon12.addFile("./images/Redo.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionRedo.setIcon(icon12)
        self.actionFont = QAction(MainWindow)
        self.actionFont.setObjectName(u"actionFont")
        icon13 = QIcon()
        icon13.addFile("./images/Font-family.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionFont.setIcon(icon13)
        self.actionColor = QAction(MainWindow)
        self.actionColor.setObjectName(u"actionColor")
        icon14 = QIcon()
        icon14.addFile("./images/color.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionColor.setIcon(icon14)
        self.actionBold = QAction(MainWindow)
        self.actionBold.setObjectName(u"actionBold")
        icon15 = QIcon()
        icon15.addFile("./images/bold.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionBold.setIcon(icon15)
        self.actionItalic = QAction(MainWindow)
        self.actionItalic.setObjectName(u"actionItalic")
        icon16 = QIcon()
        icon16.addFile("./images/Italics.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionItalic.setIcon(icon16)
        self.actionUnderline = QAction(MainWindow)
        self.actionUnderline.setObjectName(u"actionUnderline")
        icon17 = QIcon()
        icon17.addFile("./images/underline.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionUnderline.setIcon(icon17)
        self.actionLeft = QAction(MainWindow)
        self.actionLeft.setObjectName(u"actionLeft")
        icon18 = QIcon()
        icon18.addFile("./images/Left-align.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionLeft.setIcon(icon18)
        self.actionCenter = QAction(MainWindow)
        self.actionCenter.setObjectName(u"actionCenter")
        icon19 = QIcon()
        icon19.addFile("./images/center-align.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionCenter.setIcon(icon19)
        self.actionRight = QAction(MainWindow)
        self.actionRight.setObjectName(u"actionRight")
        icon20 = QIcon()
        icon20.addFile("./images/Right-align.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionRight.setIcon(icon20)
        self.actionJustify = QAction(MainWindow)
        self.actionJustify.setObjectName(u"actionJustify")
        icon21 = QIcon()
        icon21.addFile("./images/Justify.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionJustify.setIcon(icon21)
        self.actionTime = QAction(MainWindow)
        self.actionTime.setObjectName(u"actionTime")
        icon22 = QIcon()
        icon22.addFile("./images/time.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionTime.setIcon(icon22)
        self.actionDate = QAction(MainWindow)
        self.actionDate.setObjectName(u"actionDate")
        icon23 = QIcon()
        icon23.addFile("./images/date.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionDate.setIcon(icon23)
        self.actionText_Highlight = QAction(MainWindow)
        self.actionText_Highlight.setObjectName(u"actionText_Highlight")
        icon24 = QIcon()
        icon24.addFile("./images/text-highlighter.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionText_Highlight.setIcon(icon24)
        self.actionAbout = QAction(MainWindow)
        self.actionAbout.setObjectName(u"actionAbout")
        icon25 = QIcon()
        icon25.addFile("./images/about.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionAbout.setIcon(icon25)
        self.actionAbout_Qt = QAction(MainWindow)
        self.actionAbout_Qt.setObjectName(u"actionAbout_Qt")
        icon26 = QIcon()
        icon26.addFile("./images/Qt.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionAbout_Qt.setIcon(icon26)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.textEdit = QTextEdit(self.centralwidget)
        self.textEdit.setObjectName(u"textEdit")
        self.textEdit.setGeometry(QRect(0, -10, 791, 571))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 793, 21))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuEdit = QMenu(self.menubar)
        self.menuEdit.setObjectName(u"menuEdit")
        self.menuFormat = QMenu(self.menubar)
        self.menuFormat.setObjectName(u"menuFormat")
        self.menuStyle = QMenu(self.menubar)
        self.menuStyle.setObjectName(u"menuStyle")
        self.menuTime_and_Date = QMenu(self.menubar)
        self.menuTime_and_Date.setObjectName(u"menuTime_and_Date")
        self.menuText_Highlighter = QMenu(self.menubar)
        self.menuText_Highlighter.setObjectName(u"menuText_Highlighter")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QToolBar(MainWindow)
        self.toolBar.setObjectName(u"toolBar")
        MainWindow.addToolBar(Qt.TopToolBarArea, self.toolBar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuFormat.menuAction())
        self.menubar.addAction(self.menuStyle.menuAction())
        self.menubar.addAction(self.menuTime_and_Date.menuAction())
        self.menubar.addAction(self.menuText_Highlighter.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionPrint)
        self.menuFile.addAction(self.actionPrint_Preview)
        self.menuFile.addAction(self.actionExport_As_PDF)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuFormat.addAction(self.actionFont)
        self.menuFormat.addAction(self.actionColor)
        self.menuStyle.addAction(self.actionBold)
        self.menuStyle.addAction(self.actionItalic)
        self.menuStyle.addAction(self.actionUnderline)
        self.menuStyle.addSeparator()
        self.menuStyle.addAction(self.actionLeft)
        self.menuStyle.addAction(self.actionCenter)
        self.menuStyle.addAction(self.actionRight)
        self.menuStyle.addAction(self.actionJustify)
        self.menuTime_and_Date.addAction(self.actionTime)
        self.menuTime_and_Date.addAction(self.actionDate)
        self.menuText_Highlighter.addAction(self.actionText_Highlight)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionAbout_Qt)
        self.toolBar.addAction(self.actionPrint)
        self.toolBar.addAction(self.actionPrint_Preview)
        self.toolBar.addAction(self.actionExport_As_PDF)
        self.toolBar.addAction(self.actionNew)
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addAction(self.actionSave_As)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionCopy)
        self.toolBar.addAction(self.actionCut)
        self.toolBar.addAction(self.actionPaste)
        self.toolBar.addAction(self.actionUndo)
        self.toolBar.addAction(self.actionRedo)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionFont)
        self.toolBar.addAction(self.actionColor)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionBold)
        self.toolBar.addAction(self.actionItalic)
        self.toolBar.addAction(self.actionUnderline)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionLeft)
        self.toolBar.addAction(self.actionCenter)
        self.toolBar.addAction(self.actionRight)
        self.toolBar.addAction(self.actionJustify)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionTime)
        self.toolBar.addAction(self.actionDate)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionNew.setText(QCoreApplication.translate("MainWindow", u"New", None))
        self.actionOpen.setText(QCoreApplication.translate("MainWindow", u"Open", None))
        self.actionSave.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.actionSave_As.setText(QCoreApplication.translate("MainWindow", u"Save As", None))
        self.actionPrint.setText(QCoreApplication.translate("MainWindow", u"Print", None))
        self.actionPrint_Preview.setText(QCoreApplication.translate("MainWindow", u"Print Preview", None))
        self.actionExport_As_PDF.setText(QCoreApplication.translate("MainWindow", u"Export As PDF", None))
        self.actionExit.setText(QCoreApplication.translate("MainWindow", u"Exit", None))
        self.actionCopy.setText(QCoreApplication.translate("MainWindow", u"Copy", None))
        self.actionCut.setText(QCoreApplication.translate("MainWindow", u"Cut", None))
        self.actionPaste.setText(QCoreApplication.translate("MainWindow", u"Paste", None))
        self.actionUndo.setText(QCoreApplication.translate("MainWindow", u"Undo", None))
        self.actionRedo.setText(QCoreApplication.translate("MainWindow", u"Redo", None))
        self.actionFont.setText(QCoreApplication.translate("MainWindow", u"Font", None))
        self.actionColor.setText(QCoreApplication.translate("MainWindow", u"Color", None))
        self.actionBold.setText(QCoreApplication.translate("MainWindow", u"Bold", None))
        self.actionItalic.setText(QCoreApplication.translate("MainWindow", u"Italic", None))
        self.actionUnderline.setText(QCoreApplication.translate("MainWindow", u"Underline", None))
        self.actionLeft.setText(QCoreApplication.translate("MainWindow", u"Left", None))
        self.actionCenter.setText(QCoreApplication.translate("MainWindow", u"Center", None))
        self.actionRight.setText(QCoreApplication.translate("MainWindow", u"Right", None))
        self.actionJustify.setText(QCoreApplication.translate("MainWindow", u"Justify", None))
        self.actionTime.setText(QCoreApplication.translate("MainWindow", u"Time", None))
        self.actionDate.setText(QCoreApplication.translate("MainWindow", u"Date", None))
        self.actionText_Highlight.setText(QCoreApplication.translate("MainWindow", u"Text Highlight", None))
        self.actionAbout.setText(QCoreApplication.translate("MainWindow", u"About", None))
        self.actionAbout_Qt.setText(QCoreApplication.translate("MainWindow", u"About Qt", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuEdit.setTitle(QCoreApplication.translate("MainWindow", u"Edit", None))
        self.menuFormat.setTitle(QCoreApplication.translate("MainWindow", u"Format", None))
        self.menuStyle.setTitle(QCoreApplication.translate("MainWindow", u"Style", None))
        self.menuTime_and_Date.setTitle(QCoreApplication.translate("MainWindow", u"Time And Date", None))
        self.menuText_Highlighter.setTitle(QCoreApplication.translate("MainWindow", u"Text Highlighter", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"Help", None))
        self.toolBar.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar", None))
    # retranslateUi

